# [advice from AI] cert-manager ClusterIssuer 설정
# Let's Encrypt Staging (테스트용)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt Staging 서버 (테스트용, 레이트 리밋 없음)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@timbel.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Let's Encrypt Production (실제 운영용)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt Production 서버
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@timbel.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Self-Signed Issuer (로컬 개발용)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
